"""add_transcript_is_redacted

Revision ID: 5c54be514aa4
Revises: e4105de01ace
Create Date: 2026-09-19 12:54:04.795650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c54be514aa4'
down_revision: Union[str, Sequence[str], None] = 'e4105de01ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('is_redacted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'is_redacted')
    # ### end Alembic commands ###
