"""add_retailer_plan_data

Revision ID: ca0b1a0e9127
Revises: 5c54be514aa4
Create Date: 2026-09-19 15:49:34.258264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca0b1a0e9127'
down_revision: Union[str, Sequence[str], None] = '5c54be514aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retailers', sa.Column('plan_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retailers', 'plan_data')
    # ### end Alembic commands ###
